### ISSUE TITLE
can you update the readme ?

### ISSUE THREAD

**Issue by moxgeek** [billsioros/CMeans#1]
hello
can you update the readme with more details 
as an example of file ( argements ) commends , etc ... ?

**Comment by billsioros** [comment]
Hello

I have updated the readme. Bare in mind that main.cpp is only a dummy example.
If you believe anything needs any further clarification, please notify me and i ll update it.

Sorry for the late response and thank u for taking an interest into my work

Edit: If you'd prefer something a single executable that u only need to specify the input arguements, say so :)
